from __future__ import annotations

# Internal-ID -> Unity inventory-art names confirmed by the user during manual
# review. Treat this as the durable source of truth for mappings Bruno gives us.
USER_CONFIRMED_SPRITE_ALIASES: dict[str, tuple[str, ...]] = {
    "candy_1": ("rocketCandy_inv",),
    "cattaram_geode": ("cattaram_geode_inv",),
    "cattaram_mine": ("cattaram_mine_inv",),
    "cattaram_stone": ("cattaram_stone_inv",),
    "demonic_eye": ("demonicAye_inv",),
    "dog_meat": ("dog_meat_inv",),
    "dog_skin": ("dog_skin_inv",),
    "dog_skull": ("dog_skull_inv",),
    "dog_teeth": ("dog_teeth_inv",),
    "human_ear": ("humanEar_icon",),
    "human_eye": ("human_aye_icon",),
    "human_meat": ("meat1_inv",),
    "human_organ_1": ("furuncle_inv",),
    "human_poop": ("poopIcon",),
    "human_rib": ("humanRig_icon",),
    "human_skin": ("skinIcon",),
    "human_skull": ("humanSkull_icon",),
    "impaler": ("impaler_inv",),
    "jupiter_goulash": ("jupiter_goulash_inv",),
    "jupiter_grass": ("jupiter_grass_inv",),
    "jupiter_guts": ("jupiter_guts_inv",),
    "jupiter_mushrooms": ("jupiter_mushrooms_inv",),
    "mars_crab_meat": ("mars_crab_meat_inv",),
    "mars_gas_ammo": ("mars_gas_inv",),
    "mars_gear": ("mars_gear_inv",),
    "mars_skin": ("mars_skin_inv",),
    "mercury_glass": ("mercury_glass_inv",),
    "mercury_guts": ("mercury_guts_inv",),
    "mercury_rags": ("mercury_rags_inv",),
    "mercury_scales": ("mercury_scale_inv",),
    "moon_guts": ("moon_guts_inv",),
    "moon_armor_plates": ("moon_armor_inv",),
    "moon_weapon_parts": ("moon_shards_inv",),
    "precious_metals": ("precious_metals_inv",),
    "quasi_basic_ammo": ("uasi_ammo_inv",),
    "quasi_bolts_ammo": ("quasiBolts_inv",),
    "quasi_darts_ammo": ("darts_inv",),
    "quasi_energy_ammo": ("quasi_energy_ammo_inv",),
    "quasi_grenade": ("quasi_grenade_inv",),
    "quasi_medical_kit_1": ("demonicMeds_inv",),
    "quasi_repair_kit": ("demonicShards_inv",),
    "quasi_ron_medicine_1": ("ron_med_inv",),
    "quasi_venus_feather": ("venus_feather_inv",),
    "quasi_venus_rags": ("aztec_rags_inv",),
    "roasted_dog_meat": ("roasted_dog_meat_inv",),
    "roasted_human_skin": ("slanina_inv",),
    "roasted_human_meat": ("roastedMeat1_inv",),
    "roasted_mars_crab_meat": ("roasted_mars_crab_meat_inv",),
    "roasted_ron_tentacle": ("roasted_ron_tentacle_inv",),
    "roasted_spider_meat": ("roasted_spider_meat_inv",),
    "ron_blood": ("ron_blood_inv",),
    "ron_mask_1": ("ron_mask_inv",),
    "ron_moonshine": ("ron_moonshine_inv",),
    "ron_tentacle": ("ron_tentacle_inv",),
    "rotten_dog_meat": ("rotten_dog_meat_inv",),
    "rotten_human_meat": ("rottenMeat1_inv",),
    "rotten_human_skin": ("rotten_human_skin",),
    "rotten_soup_can_1": ("rotten_soup_inv",),
    "rotten_spider_meat": ("rotten_spider_meat_inv",),
    "skrivnus_knife": ("skrivnus_knife_inv",),
    "soup_can_1": ("spider_soup_inv",),
    "spider_brain": ("spiderBrain_icon",),
    "spider_chitin": ("spiderChitin_icon",),
    "spider_eye": ("spiderAye_icon",),
    "spider_joint": ("spiderJoint_icon",),
    "spider_meat": ("spiderMeat_icon",),
    "spore_mine": ("spore_mine_inv",),
    "syringe_bloodbag": ("bloodBag_inv",),
    "throwable_heart": ("heart_icon",),
    "urparp_grenade": ("urparp_grenade_inv",),
    "venus_armor_plates": ("venus_shard_inv",),
    "venus_guts": ("aztec_guts_inv",),
    "venus_melee_parts": ("venus_melee_inv",),
    "venus_weapon_parts": ("aztKey_inv",),
}

USER_CONFIRMED_SPRITE_OBJECTS: dict[
    str,
    dict[str, tuple[int, ...] | tuple[str, ...]],
] = {
    "moon_armor_plates": {
        "asset_names": ("moon_armor_inv",),
        "texture_path_ids": (6786,),
        # The AssetRipper SpriteInformationObject points to Sprite PathID
        # 20834. The user also identified the visible sprite entry as 6791.
        "sprite_path_ids": (6791, 20834),
    },
}
